# This script tests if the server has dependencies and reaches the point of starting its server.

# Run with `expect -f test_startup.exp`

set timeout 10

# This matches the Dockerfile command, but we listen on localhost to avoid risking laptop
set child_pid [spawn env HOST=localhost PORT=8001 uv run --no-sync server]

expect {
    "Uvicorn running on" {
        puts "Spawned pid was $child_pid"
        exec pkill -P $child_pid
        puts "Success"; exit 0
    }
    timeout {
        exec kill -9 $child_pid
        puts "Timed out waiting for startup"; exit 1
    }
    eof { puts "Process exited early; exit 2 }
}
